##
## Makefile for corewar in /home/sid/CPE_2016_corewar
## 
## Made by Sid
## Login   <sid.djilali-saiah@epitech.eu>
## 
## Started on  Mon Apr  3 00:10:48 2017 Sid
## Last update Sun Apr  2 23:42:59 2017 Sid
##

all:
	make -C asm/
	make -C vm/

re:
	make re -C asm/
	make re -C vm/

clean:

	make clean -C asm/
	make clean -C vm/

fclean:
	make fclean -C asm/
	make fclean -C vm/
